version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-and-products-app-test
    ports:
      - '8000:3000'
      - '8001:9876'
    volumes:
      - .:/app
      - /app/node-modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "start"]