import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import RootLayout from "./layout";

export default function ServerLayout({ children }: { children: React.ReactNode }) {
  return <RootLayout>{children}</RootLayout>;
}